name: Morphe Hybrid Check & Patch
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  check:
    name: Check new Morphe Beta patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Check new patch Morphe Beta
        id: check-morphe-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh MorpheApp/morphe-patches prerelease youtube-beta-morphe.apk
    outputs:
      new_patch: ${{ steps.check-morphe-beta.outputs.new_patch }}

  Patch-Morphe-Hybrid:
    name: Patch Morphe Hybrid
    needs: check
    if: ${{ needs.check.outputs.new_patch == 1 || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Cache APK downloads
        id: cache-apk
        uses: actions/cache@v4
        with:
          path: ./download
          key: apk-${{ runner.os }}-${{ hashFiles('src/build/morphe-hybrid.sh') }}-${{ github.sha }}
          restore-keys: |
            apk-${{ runner.os }}-${{ hashFiles('src/build/morphe-hybrid.sh') }}-
            apk-${{ runner.os }}-
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-morphe-hybrid
        run: bash src/etc/connection.sh
      - name: Check experimental support versions
        id: experimental-check
        if: steps.check-gh-morphe-hybrid.outputs.internet_error == '0'
        uses: ./.github/actions/experimental-check
      - name: Patch apk
        id: patch-morphe-hybrid
        if: steps.check-gh-morphe-hybrid.outputs.internet_error == '0'
        env:
          youtube_experimental_support: ${{ steps.experimental-check.outputs.youtube_experimental_support }}
          youtube_music_experimental_support: ${{ steps.experimental-check.outputs.youtube_music_experimental_support }}
          reddit_experimental_support: ${{ steps.experimental-check.outputs.reddit_experimental_support }}
        run: bash src/build/morphe-hybrid.sh all
      - name: Releasing APK files
        id: release-morphe-hybrid
        if: steps.check-gh-morphe-hybrid.outputs.internet_error == '0'
        uses: ./.github/actions/release-morphe-hybrid